### ISSUE TITLE
Problem with headers not displaying (local) (linux)

### ISSUE THREAD

**Issue by EIREXE** [KerbalStuff/KerbalStuff#100]
I made a similar issue to this one before, and it was on windows, since I was told there is no windows support, I got a ubuntu server virtual machine on hyper-v and I get the exact same issue on it.

I upload the header, the loadbar pops up and then I get a "done" text, but instead of the expected movable image in the background, I get a white one, saving the changes makes my header picture white.
![image](https://cloud.githubusercontent.com/assets/3101690/7330965/8eee62de-eafc-11e4-8074-c898f30a3be3.png)

**Comment by SirCmpwn** [comment]
Can you do the same procedure with the network panel open and send along a screenshot of it?

**Comment by EIREXE** [comment]
Oh I see, it doesn't find the content folder because the server is not serving it, I'm currently using the dev server (simply running app.py), would running it from gunicorn fix it?

**Comment by SirCmpwn** [comment]
The generally recommended way is to serve it through nginx. Here's the config I use for development: https://gist.github.com/SirCmpwn/4cc7f27846122c20224c

**Comment by EIREXE** [comment]
Alright, thanks!
