### ISSUE TITLE
Addresses unexpectedly reaching 404

### ISSUE THREAD

**Issue by plague006** [KerbalStuff/KerbalStuff#111]
https://kerbalstuff.com/mod/651/ results in a 404 while https://kerbalstuff.com/mod/651 and https://kerbalstuff.com/mod/651/somestuff properly resolve to the mod's page. Would it be possible to have the mod pages resolve as expected with a URL ending in a slash?

**Comment by SirCmpwn** [comment]
No. You only get broken URLs if you edit them yourself, and that's not supported.
