### ISSUE TITLE
KerbalStuff is very slow lately

### ISSUE THREAD

**Issue by Olympic1** [KerbalStuff/KerbalStuff#122]
I have an internet connection of 20 Mb/s and can download anything very quick, but when I download something from KerbalStuff, it downloads the zip file with 1-2 Mb/s. A week ago (or more) it downloaded much quicker then now.

This also affects CKAN when downloading from KS.

**Comment by Joshwoo69** [comment]
same effect on my end.
might consider upgrading some servers or checking what is taking a long time.
