### ISSUE TITLE
Forum migration broke all the old links

### ISSUE THREAD

**Issue by Olympic1** [KerbalStuff/KerbalStuff#125]
The KSP forums are migrated from `vBulletin` to `IPS`, unfortunaly this migration broke all the old forum links. I asked KasperVld if he could make a redirection script so that the old links redirect the user to the new links, but looks like that isn't possible.

> Olympic1: I noticed that the old links doesn't work anymore, I thought you would redirect them to the respective thread.

> KasperVld: Turns out it's not possible, sorry. I did look into it though.

Turns out that the new forum links also need to have to be changed

Old forum link
http://forum.kerbalspaceprogram.com/threads/100067

New Link
http://forum.kerbalspaceprogram.com/index.php?/topic/100067-/

**Comment by SirCmpwn** [comment]
Will send out an email to modders and have them update their links as they see fit.

**Comment by Olympic1** [comment]
Thx
