### ISSUE TITLE
KerbalStuff Domain/Database migration options?

### ISSUE THREAD

**Issue by ghost** [KerbalStuff/KerbalStuff#132]
If, and it is a big if, the community decides to take over the yoke of running and administrating the site:

What are the options to move either the domain name or the database or both?
- Can user accounts be migrated with a data dump, when bcrypt handles the encryption of passwords?
- If not, can hosted mods be inactivated until they are claimed in some way by a new user?
- Would @SirCmpwn be amenable to transferring the domain name, or providing a data dump?

And if all of that is possible, the new KerbalStuff should have a team of people to spread the weight, but that's another issue.

**Comment by ghost** [comment]
> And if all of that is possible, the new KerbalStuff should have a team of people to spread the weight, but that's another issue.

Since there's a ton of [interest to restart KerbalStuff on Reddit at least](https://www.reddit.com/r/KerbalSpaceProgram/comments/45w3eb/kerbalstuff_is_shutting_down/d00k390), if there's enough folks around, I will set up a GitHub organization, if @SirCmpwn doesn't want to transfer all the things.

**Comment by amankd** [comment]
https://www.facebook.com/groups/1702472480029005/ if you think you can lend a hand

**Comment by godarklight** [comment]
Anyone willing to help, jump on irc.esper.net - #ckan and #kspmodders. Atm VITAS is setting up kerbalstuff on his machine.

**Comment by amankd** [comment]
how?

**Comment by godarklight** [comment]
Posting the webchat link here
https://kiwiirc.com/client/irc.esper.net

**Comment by inigma2** [comment]
thanks gdl.
