### ISSUE TITLE
Can't add header

### ISSUE THREAD

**Issue by EIREXE** [KerbalStuff/KerbalStuff#99]
I tried to add a header and this is what happened, it said done and then it returned to click to upload, if I click save this happens.

![image](https://cloud.githubusercontent.com/assets/3101690/7327233/e21eef36-eacb-11e4-946e-c71bbc00d6d9.png)

**Comment by SirCmpwn** [comment]
That looks like you're running locally (as opposed to kerbalstuff.com)?

**Comment by EIREXE** [comment]
Oh, of course, is that the issue?

**Comment by SirCmpwn** [comment]
No, but it changes how I help you solve it. Is your storage directory set correctly in your `config.ini`? If you click "Download" do you get your zip file correctly? Does the image appear correctly in your storage directory? And is there any interesting output on the console?

**Comment by EIREXE** [comment]
Yes I made a folder named storage and added my full storage path (E:\skyrim\KerbalStuff\storage\) and the file does appear.

![image](https://cloud.githubusercontent.com/assets/3101690/7327399/27abddd8-eacd-11e4-834a-205592781b49.png)

**Comment by SirCmpwn** [comment]
You're running Kerbal Stuff on Windows? That's not supported, good luck.

**Comment by EIREXE** [comment]
Can you reopen this? I just tired under linux and I get the exactly same problem.
